apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/enterprise-contract/ec-cli?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch
      == "main"
    pipelinesascode.tekton.dev/pipeline: ".tekton/cli-build.yaml"
  labels:
    appstudio.openshift.io/application: ec-main-ci
    appstudio.openshift.io/component: cli-main-ci
    pipelines.appstudio.openshift.io/type: build
  name: cli-main-ci-on-pull-request
  namespace: rhtap-contract-tenant
spec:
  params:
  - name: dockerfile
    value: Dockerfile.dist
  - name: git-url
    value: '{{source_url}}'
  - name: image-expires-after
    value: 5d
  - name: output-image
    value: quay.io/redhat-user-workloads/rhtap-contract-tenant/ec-main-ci/cli-main-ci:on-pr-{{revision}}
  - name: path-context
    value: .
  - name: revision
    value: '{{revision}}'
  - name: prefetch-input
    value: '[{"type": "gomod"}, {"type": "rpm"}]'
  - name: build-source-image
    value: 'true'
  - name: build-args-file
    value: quick-build-args.conf
  - name: hermetic
    value: 'true'
  pipelineRef:
    name: cli-build
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
