name: Release

on:
  push:
    branches:
      - main

jobs:
  Build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go environment
        uses: actions/setup-go@v3.0.0
        with:
          go-version: 1.17

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: Build
        run: make

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          name: Development snapshot
          body: Unstable development snapshot release.
          tag_name: snapshot
          generate_release_notes: true
          files: dist/*
